server:
  port: 6666

logging:
  path: classpath:conf/logback.xml

logging.level:
  org.springframework: error
  org.apache.shiro: error
  org.hibernate.SQL: error
  com.research.repair: debug

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.160.16.219:3306/sunwenjuan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: yjy_tm
    password: Hc2018@call

mybatis:
  type-aliases-package: com.research.repair.model
  mapper-locations:
    - mapper/*
